version: 0.2
run-as: root
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - rm -f /usr/local/bin/php*
      - rm -f /usr/local/bin/phar*
      - rm -f /usr/local/bin/pear*
      - rm -f /usr/local/bin/pecl*
      - apt-get update
      - apt-get upgrade -y
      - apt-get install -y php7.3-cli php7.3-zip
      - phpenmod intl
      - npm install
      - npm install -g serverless
  #  pre_build:
  #    commands:
  #      - command
  build:
    commands:
      - . ./build.sh
#  post_build:
#    commands:
#      - . ./test.sh
